import { useMemo, useState } from 'react';
import { Sparkles } from 'lucide-react';
import BottomNav from './components/BottomNav';
import EmptyState from './components/EmptyState';
import GenerateResultCard from './components/GenerateResultCard';
import GuideModal from './components/GuideModal';
import MiniPlayer from './components/MiniPlayer';
import Modal from './components/Modal';
import MusicCard from './components/MusicCard';
import SectionTitle from './components/SectionTitle';
import SharePoster from './components/SharePoster';
import WuxingCard from './components/WuxingCard';
import { DISCLAIMER } from './constants';
import { audioSources } from './data/audioSources';
import { libraryTracks } from './data/library';
import { wuxingList, wuxingMap } from './data/wuxing';
import KnowledgePage from './pages/KnowledgePage';
import type { GenerateOptions, GeneratedMusic, TabKey, WuxingId } from './types';
import { generateMusic } from './utils/generateMusic';
import { getRecommendedWuxingByScene, getSeasonalWuxing, getSolarTermRecommendation } from './utils/recommend';
import { clearFavorites, clearHistory, getFavorites, getHistory, removeFavorite, saveFavorite, saveHistory } from './utils/storage';

const styles = ['古典','禅意','国潮','冥想','环境音乐','睡前轻音'] as const;
export default function App(){
const [tab,setTab]=useState<TabKey>('home'); const [wuxingId,setWuxingId]=useState<WuxingId>('water'); const [scene,setScene]=useState('睡前'); const [instruments,setIns]=useState<string[]>(['古琴低音']); const [nature,setNature]=useState('夜雨'); const [duration,setDuration]=useState<5|15|30|60>(30); const [style,setStyle]=useState<GenerateOptions['style']>('睡前轻音'); const [loading,setLoading]=useState(false); const [result,setResult]=useState<GeneratedMusic|null>(null); const [tick,setTick]=useState(0); const [search,setSearch]=useState(''); const [shareOpen,setShareOpen]=useState(false); const [aboutOpen,setAboutOpen]=useState(false); const [sourceHelpOpen,setSourceHelpOpen]=useState(false); const [sourceRecordOpen,setSourceRecordOpen]=useState(false); const [guideOpen,setGuideOpen]=useState(()=>!localStorage.getItem('hasSeenGuide'));
const wx=wuxingMap[wuxingId]; const favorites=useMemo(()=>getFavorites(),[tick]); const history=useMemo(()=>getHistory(),[tick]);
const isValid = Boolean(wuxingId && scene && instruments.length > 0 && nature && duration && style);
const doGenerate=(opt?:Partial<GenerateOptions>)=>{setLoading(true);setTimeout(()=>{const m=generateMusic({wuxingId,scene,instruments,natureSound:nature,duration,style,...opt});saveHistory(m);setResult(m);setLoading(false);setTab('generate');setTick(v=>v+1);},800)};
const similar=()=>{if(!result) return; const b=wuxingMap[wuxingId]; doGenerate({instruments:b.mainInstruments.sort(()=>Math.random()-0.5).slice(0,2),natureSound:b.natureSounds[Math.floor(Math.random()*b.natureSounds.length)]});};
const seasonal = wuxingMap[getSeasonalWuxing()]; const solar = getSolarTermRecommendation();
const tracks=[...history,...libraryTracks].filter(m=>`${m.title}${m.wuxing}${m.scene}${m.instruments.join('')}`.includes(search));
return <div className='mx-auto min-h-screen max-w-[430px] pb-20'><main className='px-4 py-3 space-y-3'>
{tab==='home'&&<><div className='rounded-3xl bg-gradient-to-br from-slate-900 via-slate-700 to-slate-800 p-5 text-white shadow-ink'><h1 className='text-3xl font-bold'>五音生乐</h1><p className='mt-1 text-sm opacity-90'>宫商角徵羽，一音一五行。</p><p className='mt-2 text-sm opacity-80'>以《黄帝内经》五音体系为灵感，融合五行、乐器、自然声与东方意境，生成属于你的五行音乐。</p><div className='mt-3 flex gap-2'><button className='rounded-xl bg-white px-3 py-2 text-slate-900' onClick={()=>setTab('generate')}>开始生成</button><button className='rounded-xl bg-white/20 px-3 py-2' onClick={()=>setTab('library')}>浏览曲库</button></div></div>
<div className='rounded-2xl bg-white/80 p-4'><p className='text-xs text-slate-500'>今日五音</p><p className='font-semibold'>今日推荐：{seasonal.wuxing}行{seasonal.tone}</p><p className='text-sm text-slate-600'>推荐场景：{seasonal.scenes[0]} · 推荐乐器：{seasonal.mainInstruments.slice(0,2).join('、')}</p><button className='mt-2 rounded-lg bg-slate-900 px-3 py-1 text-white text-sm' onClick={()=>{setWuxingId(seasonal.id);setScene(seasonal.scenes[0]);setTab('generate')}}>生成今日五音</button></div>
<div className='rounded-2xl bg-white/80 p-4'><p className='text-xs text-slate-500'>节气推荐入口</p><p>今日宜听：{solar.tone}</p><p className='text-sm'>推荐曲：《{solar.title}》</p><p className='text-xs text-slate-600'>{solar.note}</p></div>
<SectionTitle title='场景入口'/><div className='flex flex-wrap gap-2'>{['睡前','晨起','茶室','冥想','阅读','空谷','山林','午后'].map(s=><button className='rounded-full bg-white px-3 py-1 text-sm' key={s} onClick={()=>{setScene(s);setWuxingId(getRecommendedWuxingByScene(s)[0]);setTab('generate')}}>{s}</button>)}</div>
<p className='text-[11px] text-slate-500'>{DISCLAIMER}</p></>}
{tab==='generate'&&<><h2 className='text-lg font-semibold'>生成一首五行音乐</h2><div className='space-y-3'><div><SectionTitle title='1. 选择五行'/><div className='space-y-2'>{wuxingList.map(i=><WuxingCard key={i.id} item={i} active={wuxingId===i.id} onClick={()=>setWuxingId(i.id)}/>)}</div></div><div><SectionTitle title='2. 选择场景'/><div className='flex flex-wrap gap-2'>{wx.scenes.map(s=><button key={s} className={`rounded-full px-3 py-1 text-sm ${scene===s?'bg-slate-900 text-white':'bg-white'}`} onClick={()=>setScene(s)}>{s}</button>)}</div></div><div><SectionTitle title='3. 选择乐器'/><div className='flex flex-wrap gap-2'>{wx.mainInstruments.map(ins=><button key={ins} className={`rounded-full px-3 py-1 text-sm ${instruments.includes(ins)?'bg-slate-900 text-white':'bg-white'}`} onClick={()=>setIns(v=>v.includes(ins)?v.filter(i=>i!==ins):v.length<3?[...v,ins]:(alert('最多选择三种主声音色'),v))}>{ins}</button>)}</div></div><div><SectionTitle title='4. 选择自然声'/><div className='flex flex-wrap gap-2'>{wx.natureSounds.map(n=><button key={n} className={`rounded-full px-3 py-1 text-sm ${nature===n?'bg-slate-900 text-white':'bg-white'}`} onClick={()=>setNature(n)}>{n}</button>)}</div></div><div><SectionTitle title='5. 选择时长'/><div className='flex gap-2'>{([5,15,30,60] as const).map(d=><button key={d} className={`rounded-xl px-3 py-1 ${duration===d?'bg-slate-900 text-white':'bg-white'}`} onClick={()=>setDuration(d)}>{d}分钟</button>)}</div></div><div><SectionTitle title='6. 选择风格'/><div className='flex flex-wrap gap-2'>{styles.map(s=><button key={s} className={`rounded-full px-3 py-1 text-sm ${style===s?'bg-slate-900 text-white':'bg-white'}`} onClick={()=>setStyle(s)}>{s}</button>)}</div></div></div>
<button disabled={!isValid||loading} onClick={()=>doGenerate()} className='mt-4 w-full rounded-xl bg-slate-900 py-3 text-white disabled:opacity-40'>生成我的五音曲</button>{loading&&<div className='py-2 text-sm flex items-center gap-2'><Sparkles className='animate-spin' size={16}/>正在调和五音，生成东方声境……</div>}
{result&&<div className='space-y-2'><GenerateResultCard music={result}/><MiniPlayer music={result}/><p className='text-[11px] text-slate-500'>audioUrl: {result.audioUrl || '无'} · sampleMode: {result.sampleMode || '无'}</p><p className='text-xs text-slate-600'>音源模式：{result.sampleMode==='single-file'?'真实音源':'模拟播放'}</p>{result.personalUseOnly&&<p className='text-xs text-amber-700'>当前音源为个人本地体验用途，请勿直接公开传播。</p>}{result.sampleMode==='single-file'&& !result.audioUrl &&<p className='text-xs text-rose-700'>请将音频文件放入 public/samples 对应目录后刷新页面。</p>}<div className='flex flex-wrap gap-2 text-sm'><button className='rounded bg-white px-3 py-1' onClick={()=>{saveFavorite(result);setTick(t=>t+1)}}>收藏</button><button className='rounded bg-white px-3 py-1' onClick={similar}>生成相似曲</button><button className='rounded bg-white px-3 py-1' onClick={()=>doGenerate()}>重新生成</button><button className='rounded bg-white px-3 py-1' onClick={()=>setShareOpen(true)}>分享海报</button><button className='rounded bg-white px-3 py-1' onClick={()=>setTab('home')}>返回首页</button></div><p className='text-[11px] text-slate-500'>{DISCLAIMER}</p></div>}</>}
{tab==='library'&&<><input value={search} onChange={e=>setSearch(e.target.value)} placeholder='搜索曲名、五行、乐器、场景' className='w-full rounded-xl border p-2 text-sm'/><div className='space-y-2'>{tracks.slice(0,40).map(m=><MusicCard key={m.id} music={m} onFavorite={()=>{saveFavorite(m);setTick(t=>t+1)}}/>)}{tracks.length===0&&<EmptyState text='没有找到相关音乐，试试换一个五行或乐器。'/>}</div></>}
{tab==='knowledge'&&<KnowledgePage/>}
{tab==='mine'&&<><SectionTitle title='我的收藏'/>{favorites.length?favorites.map(m=><div key={m.id} className='rounded-xl bg-white/80 p-3'><p>《{m.title}》</p><button className='text-xs text-rose-600' onClick={()=>{removeFavorite(m.id);setTick(t=>t+1)}}>取消收藏</button></div>):<EmptyState text='还没有收藏音乐，去生成一首属于你的五音曲吧。'/>}<SectionTitle title='生成历史'/>{history.length?history.slice(0,8).map(m=><p key={m.id} className='rounded-xl bg-white/80 p-2 text-sm'>《{m.title}》-{m.scene}</p>):<EmptyState text='这里还没有音乐，去生成一首属于你的五音曲吧。'/>}<SectionTitle title='偏好标签'/><div className='rounded-xl bg-white/80 p-3 text-sm'>你常听：{history[0]?.wuxing ?? '水行羽音'}、{history[0]?.instruments[0] ?? '古琴低音'}、{history[0]?.natureSound ?? '夜雨'}、{history[0]?.style ?? '睡前轻音'}。你偏好的声音气质是：深静、低回、柔和、安宁。</div><SectionTitle title='设置'/><div className='space-y-2'><button className='rounded bg-white px-3 py-2 text-sm' onClick={()=>confirm('确认清空历史？')&& (clearHistory(),setTick(t=>t+1))}>清空生成历史</button><button className='rounded bg-white px-3 py-2 text-sm' onClick={()=>confirm('确认清空收藏？')&& (clearFavorites(),setTick(t=>t+1))}>清空收藏</button><button className='rounded bg-white px-3 py-2 text-sm' onClick={()=>setSourceHelpOpen(true)}>音源管理说明</button><button className='rounded bg-white px-3 py-2 text-sm' onClick={()=>setSourceRecordOpen(true)}>音源来源记录</button><button className='rounded bg-white px-3 py-2 text-sm' onClick={()=>setAboutOpen(true)}>关于五音生乐</button><p className='text-[11px] text-slate-500'>{DISCLAIMER}</p></div></>}
</main><BottomNav tab={tab} setTab={setTab}/>
<Modal open={shareOpen&&!!result} onClose={()=>setShareOpen(false)}>{result&&<><SharePoster music={result}/><div className='mt-3 flex gap-2'><button className='rounded bg-slate-900 px-3 py-1 text-white text-sm' onClick={()=>alert('海报保存功能待接入')}>保存海报</button><button className='rounded bg-slate-100 px-3 py-1 text-sm' onClick={()=>setShareOpen(false)}>关闭</button></div></>}</Modal>
<Modal open={aboutOpen} onClose={()=>setAboutOpen(false)}><h3 className='text-lg font-semibold'>五音生乐</h3><p className='mt-2 text-sm text-slate-600'>五音生乐是一款基于《黄帝内经》五音体系灵感设计的东方五行音乐生成工具。用户可选择五行、五音、乐器与自然声，生成东方审美音乐卡片。当前为前端原型版本，播放为模拟效果，后续可接入真实音频与 AI 能力。</p></Modal>
<Modal open={sourceHelpOpen} onClose={()=>setSourceHelpOpen(false)}><h3 className='text-lg font-semibold'>音源管理说明</h3><ul className='mt-2 list-disc pl-5 text-sm text-slate-600 space-y-1'><li>古琴：guqin-demo.mp3 放入 public/samples/guqin/</li><li>洞箫：dongxiao-demo.mp3 放入 public/samples/dongxiao/</li><li>埙：xun-demo.mp3 放入 public/samples/xun/</li><li>磬：qing-demo.mp3 放入 public/samples/qing/</li><li>自然声：rain.mp3 放入 public/samples/nature/</li></ul></Modal><Modal open={sourceRecordOpen} onClose={()=>setSourceRecordOpen(false)}><h3 className='text-lg font-semibold'>音源来源记录</h3><div className='mt-2 space-y-2 max-h-72 overflow-auto'>{audioSources.map(a=><div key={a.id} className='rounded bg-slate-50 p-2 text-xs'><p className='font-medium'>{a.displayName}（{a.fileName}）</p><p>来源：{a.sourceName||'未填写，建议补充音源来源信息。'}</p><p>作者：{a.author||'未填写，建议补充音源来源信息。'}</p><p>授权：{a.license||'未填写，建议补充音源来源信息。'}</p><p>备注：{a.note||'-'}</p></div>)}</div></Modal><GuideModal open={guideOpen} onClose={()=>{localStorage.setItem('hasSeenGuide','1');setGuideOpen(false);}}/>
</div>}
